services:
  mongo-db:
    container_name: name-db_mongo
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: despliegue
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db 
      - ./database/init.js:/docker-entrypoint-initdb.d/init.js:ro
    networks:
      - datos-network

  node-js-cont:
    container_name: node-js-conter
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - datos-network

networks:
  datos-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local